export const ADD_INGREDIENT="ADD_INGREDIENT"
export const REMOVE_INGREDIENT="REMOVE_INGREDIENT"

export const SET_INGREDIENTS="SET_INGREDIENTS"
export const FETCH_INGREDIENTS="FETCH_INGREDIENTS"
export const FETCH_FAILED="FETCH_FAILED"

export const BURGER_PURCHASE_START="BURGER_PURCHASE_START"
export const BURGER_PURCHASE_SUCCESS="BURGER_PURCHASE_SUCCESS"
export const BURGER_PURCHASE_FAIL='BURGER_PURCHASE_FAIL'
export const PURCHASE_INIT="PURCHASE_INIT"
export const REDIRECT='REDIRECT' 

export const SUBMIT_ORDERS="SUBMIT_ORDERS"
export const FETCH_ORDERS_START="FETCH_ORDERS_START"
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAIL="FETCH_ORDERS_FAIL"
export const FETCH_ORDER_INIT="FETCH_ORDER_INIT"


export const CHECK_EXPIRATIOM_TIME="CHECK_EXPIRATIOM_TIME"
export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAIL="AUTH_FAIL"
export const AUTH_INITIATE_LOGOUT="AUTH_INITIATE_LOGOUT"
export const AUTH_LOGOUT="AUTH_LOGOUT"
export const AUTH_USER="AUTH_USER"
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_REDIRECT="AUTH_REDIRECT"